### ISSUE TITLE
Feature Request: Mapillary tab for download

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [JOSM/Mapillary#104]
**Problem/Motivation**
Because of the performance issues, it's hard to see whole downloaded Mapillary sequences. When we try to do it, some old computers are getting slow.

**Proposed resolution**
Enable downloading just selected Mapillary imagery sequences only,

**User interface changes**
Creating a new tab for JOSM's download screen.

**Comment by tsmock** [comment]
I'm closing this, as I've significantly adjusted how Mapillary downloads sequences.

See https://github.com/JOSM/Mapillary/releases/tag/v2.0.0-alpha.1 if you want to give feedback on the change.
