### ISSUE TITLE
Ant build is broken

### ISSUE THREAD

**Issue by don-vip** [JOSM/Mapillary#108]
https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/jdk=JDK8/1811/console

```
BUILD FAILED
/var/lib/jenkins/jobs/JOSM-Plugins/workspace/jdk/JDK8/build.xml:31: The following error occurred while executing this line:
/var/lib/jenkins/jobs/JOSM-Plugins/workspace/jdk/JDK8/build.xml:24: The following error occurred while executing this line:
/var/lib/jenkins/jobs/JOSM-Plugins/workspace/jdk/JDK8/Mapillary/build.xml:31: The prefix "if" for attribute "if:set" associated with an element type "include" is not bound.
```

**Comment by floscher** [comment]
Thanks for reporting, probably simply the namespace declaration is missing (https://ant.apache.org/manual/ifunless.html). I'll work a bit on the plugin tomorrow and look into this.

**Comment by tsmock** [comment]
This is my fault -- I wasn't checking the `ant build`, although I'm pretty certain I was running it without problems the Mac I was using. I think I was using `ant` when I authored https://gitlab.com/gokaart/josm-mapillary-plugin/-/commit/8f6310ffc66f87d1d9c394f902c9b2ddd27918ae anyway. (Not merged yet).
