### ISSUE TITLE
Manual download for Mapillary objects

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [JOSM/Mapillary#110]
When the map is zoomed out too far, JOSM hangs while downloading Mapillary objects.
Although this hang is for a few seconds, it is still annoying when panning or zooming a lot.
It would be nice if download mode can be set for Objects layer as well.

**Comment by taylorsmock** [comment]
Can you check with `v.1.5.21` or later? I think I may have (inadvertently) fixed this issue.

**Comment by GhostFoxSledgehammer** [comment]
Yes, JOSM no longer hangs for me while downloading Mapillary objects.

Also there is another problem that the object layer keeps downloading info even after the layer has been deleted. While panning this leads to many notifications if somehow it is unable to connect to Mapillary.com(no internet). Maybe i should open a new issue for this?
