### ISSUE TITLE
Sidebuttons keep stacking on Mappilary Image Dailog after walk mode

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [JOSM/Mapillary#111]
When i use walk mode the sidebuttons keep increasing until it reaches a maximum
![Screenshot (10)](https://user-images.githubusercontent.com/54080100/76346897-c0f13c00-632b-11ea-9e04-590261df38df.png) 
Then after using walk mode a few times

![Screenshot (9)](https://user-images.githubusercontent.com/54080100/76346963-d8302980-632b-11ea-9657-54b4e89e27b4.png)

**Comment by taylorsmock** [comment]
Fixed in 290cf9b662b1fb9f1da16fddafa4d47d21fbb2cf
