### ISSUE TITLE
JOSM crash on Java 14

### ISSUE THREAD

**Issue by 7RST1** [JOSM/Mapillary#122]
JOSM crashes when "rendering data" after data download. It doesn't crash with this plugin disabled.

Status report using Java 11, when JOSM is working after data download;
https://paste.ubuntu.com/p/cp4gz8DWry/
Status report using Java 14, when JOSM crashes after data download;
https://paste.ubuntu.com/p/tZYR7Hmfvx/

**Comment by tsmock** [comment]
Is this still occurring? I cannot verify since I haven't been able to reproduce. However, a stack trace from the crash would be helpful.

**Comment by 7RST1** [comment]
It seems to have been fixed. I just tried on Java **15** and the crash doesn't occur. I'll reopen if someone still experiences the issue.

**Comment by tsmock** [comment]
Thanks for looking into it again. I'm sorry I cannot be certain that the root cause is fixed.
