### ISSUE TITLE
Cannot connect to Mapillary servers

### ISSUE THREAD

**Issue by Eric-Sparks** [JOSM/Mapillary#128]
My Mapillary plugin, for some reason, will not connect to the Mapillary server to download images.  I'm not sure if this is the problem but every time I load JOSM I get a failure OpenFX error (I do have OpenJFX installed on my machine).

**Comment by taylorsmock** [comment]
JavaFX wouldn't be the issue. It would probably be a timeout issue. Is this still a problem?

**Comment by Eric-Sparks** [comment]
No, for some reason my access returned (although I'm still having the OpenFX error).  No idea...

**Comment by tsmock** [comment]
Just an FYI, recent updates to the plugin have removed the JavaFX plugin dependency.
