### ISSUE TITLE
sequence with wrong image order

### ISSUE THREAD

**Issue by Aury88** [JOSM/Mapillary#144]
I'm having some problem with the plugin (v.1.5.27) on JOSM (v. 17329) on ubuntu 20.04.
When I import  a sequence (generated by the mapillary application on my android smartphone) from a directory in my computer I obtain all the point ordered in a randomic way. (see the picture attached)
![Mapillary](https://user-images.githubusercontent.com/3192478/100705727-023ce680-33a8-11eb-89f7-8cc57c326a3d.png)

the gpx file generated by mapillary seems correct.
Here a link to a small sample containing a complete GPX but only the firsts 15 photos:
https://mega.nz/file/Nct01Zqb#QATacX5NuWxGWjvyQbF0a5F5JuWeHBYVhdY9D1sYikg

**Comment by tsmock** [comment]
Thank you for the bug report. I'm sorry it took me so long to get around to looking at and fixing. The reason that the images were sorted in a random way is that each image was added to the sequence as it was read, instead of based off of the time the picture was captured.
