### ISSUE TITLE
Cannot move or rotate imported images in Mapillary layer

### ISSUE THREAD

**Issue by Talkless** [JOSM/Mapillary#179]
Mapillary plugin in JOSM 0.0.svn14760+dfsg-1 (Debian 10 buster) works fine - I can move and rotate images, fixing their position and direction, but it completely ignores my mouse clicks & moves in Debian Sid with JOSM 0.0.svn17428+dfsg-2.

Do I have to enable some feature or use different controls..? I just use mouse drags to move, and shift+move to rotate...

**Comment by tsmock** [comment]
I hate to tell you this, but due to the v4 API change, I'm currently removing that code.

As soon as the v4 API is fully released, documented, and stable, I'll look into adding image edits back in.

See https://blog.mapillary.com/update/2021/03/03/preparing-for-the-new-mapillary-api.html for more info on the v4 api.

**Comment by Talkless** [comment]
That looks like a lot of work..? I hope you will find time and energy to make it all work!

**Comment by tsmock** [comment]
The stuff I need in JOSM core is mostly done (see https://josm.openstreetmap.de/ticket/17177 ).

I've _just_ started working on porting the plugin over to use the (unmerged) functionality. I'll probably be making a prerelease for testing. I'll ping you when I do, if you are interested.

**Comment by Talkless** [comment]
> I'll ping you when I do, if you are interested.

Sure, let me know! Though I did find "workaround" - to use `photoadjust` plugin for editing positions, it would be nice to test Mapillary too.

**Comment by Talkless** [comment]
@tsmock I'm not sure how to introduce that plugin "manaully" into JOSM..?

**Comment by tsmock** [comment]
No worries. It is available by default in the current JOSM tested. As in, if you update plugins after updating JOSM, you will get it (`alpha.5` currently).
