### ISSUE TITLE
Mapillary photo loses focus when another object is selected

### ISSUE THREAD

**Issue by govvin** [JOSM/Mapillary#180]
I just updated JOSM, and the Mapillary plugin to v 2.0.0.alpha.5

Whenever I review a photo, and then select an OSM element on the screen, the photo loses focus, the image window reports "no image selected" and then, of course, I wouldn't be able to add a Mapillary tag to the object. Extra step (that works intermittently) is to click on the photo again, and one _might_  be able to tag the object with the Mapillary photo id, from the image info window.

This wasn't the behavior in the previous version I was using.

**Comment by tsmock** [comment]
The previous behavior was triple-click deselected images. I've been meaning to reintroduce that, but my higher priority was ensuring that images could at least be viewed.

**Comment by tsmock** [comment]
Fixed in [https://github.com/JOSM/Mapillary/releases/tag/v2.0.0-alpha.6 v2.0.0-alpha.6].
