### ISSUE TITLE
Using numeric keys for Picture Filter changes map zoom level

### ISSUE THREAD

**Issue by govvin** [JOSM/Mapillary#182]
When changing the values of the "not older than" filters using the numeric keys (top of the keyboard) 1-5, the zoom level of the map changes as well. This doesn't happen when using the numeric keypad (to the right of the keyboard).

This behavior has been observed in current and previous versions of the plugin.

**Comment by tsmock** [comment]
I've fixed most of the text fields.

Exceptions:
* Date fields. I've got the choice between a UI to pick the date and not changing the zoom level. I'm defaulting to the UI picker, but you can always change the advanced preference `datepicker.classname` from `org.openstreetmap.josm.plugins.datepicker.impl.DatePickerJDatePicker` to `org.openstreetmap.josm.plugins.datepicker.impl.DatePickerSwing`.
* The object detection filter (this will require a JOSM core change, see [#20954](https://josm.openstreetmap.de/ticket/20954))
