### ISSUE TITLE
Can't login: "App not found"

### ISSUE THREAD

**Issue by floscher** [JOSM/Mapillary#183]
When I try to login in the JOSM preferences (Plugins › Mapillary tab), I can login to mapillary.com in the browser, but then it says:
![grafik](https://user-images.githubusercontent.com/3904348/121731455-3fb9c380-caf1-11eb-9211-db1fcb3e980d.png)

**Comment by floscher** [comment]
cc @mapillary: Is this OAuth client maybe out of date:
https://github.com/JOSM/Mapillary/blob/256dec3a84dc36772f3bd19e2fe6d79ac24ddb45/src/main/java/org/openstreetmap/josm/plugins/mapillary/utils/MapillaryURL.java#L24

**Comment by tsmock** [comment]
Yes. I've got a v4 API branch (I haven't tested login yet, as the v4 API was released last week -- it is on my list of things to do next week, and I'm kind of hoping "it just works"), but I ran into an API rate limit, so I reverted back to the v3 API implementation for vector tiles. I'm hoping that logged in users will not see the API rate limit, but we'll see. If so, I'll have to add something to let the user know (AKA, "Can you please login to Mapillary? We just hit the API rate limit for Mapillary.").

See https://github.com/JOSM/Mapillary/tree/josm-17177-support for that (it is the branch for vector tiles, which is all the v4 API supports).

**Comment by Talkless** [comment]
I got same issue with v1.5.37.6. JOSM updated plugin for me today.

**Comment by tsmock** [comment]
There is a whole bunch of API breakage with the new v4 API. It looks like it is going to be more difficult than I expected to get login working again. This is still a priority for me, since I'm hoping that logging in will alleviate the rate limits I noted previously.

**Comment by tsmock** [comment]
Here is an update on this:
* The implicit oauth2 workflow no longer works.
* The Mapillary OAuth2 workflow *may* be broken. I'm going to give the Mapillary guys a few days to put out other fires before I poke them.

**Comment by tsmock** [comment]
This specific issue should now be fixed.
https://github.com/JOSM/Mapillary/releases/tag/v2.0.0-alpha.22

Notes:
* It requires a client secret, which I did *not* check in to source code.
