### ISSUE TITLE
Image Viewer is not moved back to main dialog after adding to Color Picker dialog.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [JOSM/Mapillary#184]
https://github.com/JOSM/Mapillary/blob/c141f5b9a31f6c4ca6cfa0b05c8e94ce164c36e7/src/main/java/org/openstreetmap/josm/plugins/mapillary/gui/ImageColorPicker.java#L93

Here the image viewer is added to a color picker dialog which removes it from the main dialog and is never added back when the dialog is closed.

**Comment by tsmock** [comment]
You are right.

**Comment by tsmock** [comment]
I believe I fixed it in 36dc3b8. Ideally, I'd just move the color picker to to the MapillaryMainDialog, but I don't have the time to do that right now.
