### ISSUE TITLE
Make JoinMode and SelectMode subclasses of MapMode

### ISSUE THREAD

**Issue by floscher** [JOSM/Mapillary#21]
Currently JoinMode and SelectMode are completely custom built. Instead I'd like them to extend from MapMode, which is provided by JOSM-core. That would make them appear in the button-sidebar on the left below e.g. the select-mode for OSM data layers. This would be a more appropriate place for them instead of hiding in the window menu.

Here's the current inheritance hierarchy and the one I propose:
![inheritance_hierarchy](https://cloud.githubusercontent.com/assets/3904348/18674653/355946b4-7f50-11e6-869f-d9cd48c968b2.png)

**Comment by nokutu** [comment]
Looks nice, don't know why I didn't do like this at the beginning, probably wasn't aware of MapMode class.
