### ISSUE TITLE
filter by user

### ISSUE THREAD

**Issue by thibaultmol** [JOSM/Mapillary#211]
Currently you can only filter by org id. But from what i've seen user id and org id might be the same thing? So being able to filter by a user could be added, I think

**Comment by tsmock** [comment]
Last I checked, no, they are _not_ the same thing. I'd _like_ to readd that functionality, but the data just isn't publicly available.

For reference, here are the fields returned by the _public_ API tiles:
| Key | Value |
|-----|------|
|captured_at|1614937727988|
|id|75355|
|image_id|179346464136743|
|is_pano|false|
|layer|sequence|

And the fields returned by the tiles used on the Mapillary website:
| Key | Value |
|-----|------|
|captured_at|1614937727988|
|creator_id|104214208486349|
|id|132|
|image_id|179346464136743|
|is_pano|false|
|layer|sequence|

Notice the _additional_ field for `creator_id`. There is an additional field that is optionally present on the sequence, `organization_id`, but in the sample I looked at, `organization_id != creator_id`.

**Comment by tsmock** [comment]
Mapillary has added user information to the public vector tiles. This should be fixed in #230.
