### ISSUE TITLE
Single images not displayed

### ISSUE THREAD

**Issue by brunetton** [JOSM/Mapillary#219]
Hi

I'm using Mapillary plugin (last version available from Josm, ie 2.1.5) with JOSM 18789

I noticed that I can see and "browse" images from sequences, but not standalone images.

Example: [this image](https://www.mapillary.com/app/?pKey=282062357770856):
- when zooming around 44.59115,1.87328 in JOSM I only see the sequence that is near to this single image:
    ![image](https://github.com/JOSM/Mapillary/assets/86322/9ec9f20f-3c18-4582-802c-7a20e1417a9b)
- but [in Mapillary](https://www.mapillary.com/app/?lat=44.60533169215475&lng=1.8962164054848927&z=16.869404609555172&mapStyle=OpenStreetMap) I can see the single image next to the river (that I circled in red to be clear):
    ![image](https://github.com/JOSM/Mapillary/assets/86322/ef22a552-a807-45bf-ba23-b9d88d8713db)

Did I missed something ? Is it a Mapillary's API limitation ?

I really need those images for mapping.
Thanks a lot !

**Comment by tsmock** [comment]
Thank you for reporting this problem.

**Comment by brunetton** [comment]
Thanks a LOT 😍
