### ISSUE TITLE
导出jar运行报错，具体环境要求是什么？

### ISSUE THREAD

**Issue by vdjango** [JOSM/Mapillary#222]
> Task :compileJava
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\layer\PointObjectLayer.java:85: ����: [deprecation] org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit�е�IgnoredObjects�ѹ�ʱ
import org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit.IgnoredObjects;
                                                                        ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\actions\SmartEditRemoveAction.java:24: ����: [deprecation] org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit�е�IgnoredObjects�ѹ�ʱ
import org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit.IgnoredObjects;
                                                                        ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\MapillaryPlugin.java:29: ����: [deprecation] org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit�е�IgnoredObjects�ѹ�ʱ
import org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit.IgnoredObjects;
                                                                        ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\utils\ReflectionUtils.java:5: ����: [removal] java.security �е� AccessController �ѹ�ʱ, �ұ��Ϊ��ɾ��
import java.security.AccessController;
                    ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\layer\PointObjectLayer.java:184: ����: [deprecation] org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit�е�IgnoredObjects�ѹ�ʱ
        primitives.stream().filter(p -> IgnoredObjects.isIgnoredObject(p.getUniqueId()))
                                        ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\actions\SmartEditRemoveAction.java:87: ����: [deprecation] org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit�е�IgnoredObjects�ѹ�ʱ
        IgnoredObjects.addIgnoredObject(builder.build());
        ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\cache\Caches.java:142: ����: [varargs] Varargs �������ܵ������Բ��ɾ��廯 varargs ���� validators �Ķ���Ⱦ
                this.validators = Arrays.asList(validators.clone());
                                                                ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\MapillaryPlugin.java:77: ����: [deprecation] org.openstreetmap.josm.plugins.mapillary.data.mapillary.smartedit�е�IgnoredObjects�ѹ�ʱ
        IgnoredObjects.isIgnoredObject(0);
        ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\utils\MapillaryUtils.java:155: ����: [removal] System �е� getSecurityManager() �ѹ�ʱ, �ұ��Ϊ��ɾ��
        if (IS_RUNNING_WEBSTART || System.getSecurityManager() != null) {
                                         ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\utils\ReflectionUtils.java:40: ����: [removal] java.security �е� AccessController �ѹ�ʱ, �ұ��Ϊ��ɾ��
            AccessController.doPrivileged((PrivilegedExceptionAction<Void>) () -> {
            ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\utils\SecurityManagerUtils.java:21: ����: [removal] System �е� getSecurityManager() �ѹ�ʱ, �ұ��Ϊ��ɾ��
        if (System.getSecurityManager() != null) {
                  ^
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\data\mapillary\ObjectDetections.java:118: ����: [FutureReturnValueIgnored] Return value of methods returning Future must be checked. Ignoring returned Futures suppresses exceptions thrown from the code that completes the Future.
            foundIcon.getAsync(imageIcon -> {
                              ^
    (see https://errorprone.info/bugpattern/FutureReturnValueIgnored)
  Did you mean 'var unused = foundIcon.getAsync(imageIcon -> {' or to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\cache\MapillaryCache.java:64: ����: [ImmutableEnumChecker] enums should be immutable: 'Type' has field 'executor' of type 'java.util.concurrent.ThreadPoolExecutor', the declaration of type 'java.util.concurrent.ThreadPoolExecutor' is not annotated with @com.google.errorprone.annotations.Immutable
        private final ThreadPoolExecutor executor;
                                         ^
    (see https://errorprone.info/bugpattern/ImmutableEnumChecker)
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\utils\MapillaryImageUtils.java:158: ����: [FutureReturnValueIgnored] Return value of methods returning Future must be checked. Ignoring returned Futures suppresses exceptions thrown from the code that completes the Future.
                    getImage(image, type).thenAccept(completableFuture::complete);
                                                    ^
    (see https://errorprone.info/bugpattern/FutureReturnValueIgnored)
  Did you mean 'var unused = getImage(image, type).thenAccept(completableFuture::complete);' or to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\data\mapillary\ImageNavigation.java:169: ����: [UnusedVariable] The parameter 'travelAngle' is never read.
    private static Pair<Direction, VectorNode> sort(boolean isPano, boolean computed, double angle, double travelAngle,
                                                                                                           ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean 'this.originalSort = surroundingNodes.stream().map(n -> sort(isPano, false, angle, n, nodeEn))'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\dialog\MapillaryFilterDialog.java:85: ����: [UnusedVariable] The field 'TIME_FACTOR' is never read.
    private static final long[] TIME_FACTOR = new long[] { 31_536_000_000L, // = 365 * 24 * 60 * 60 * 1000 = number of
                                ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
����: [MethodCanBeStatic] A private method that does not reference the enclosing instance can be static
    (see https://errorprone.info/bugpattern/MethodCanBeStatic)
  Did you mean 'Collection<IPrimitive> currentSelection = ImageFilterPredicate.getCurrentSelection();'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\dialog\MapillaryFilterDialog.java:443: ����: [UngroupedOverloads] Overloads should be grouped together, even when modifiers such as static or private differ between the methods; found ungrouped overloads of 'test' on line(s): 465
        public boolean test(INode img) {
                       ^
    (see https://errorprone.info/bugpattern/UngroupedOverloads)
  Did you mean to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\dialog\MapillaryFilterDialog.java:465: ����: [UngroupedOverloads] Overloads should be grouped together, even when modifiers such as static or private differ between the methods; found ungrouped overloads of 'test' on line(s): 442
        public boolean test(INode img, Collection<IPrimitive> currentSelection) {
                       ^
    (see https://errorprone.info/bugpattern/UngroupedOverloads)
  Did you mean to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\ImageCheckBoxButton.java:87: ����: [FutureReturnValueIgnored] Return value of methods returning Future must be checked. Ignoring returned Futures suppresses exceptions thrown from the code that completes the Future.
                this.icon.getAsync(i -> GuiHelper.runInEDT(() -> this.image.setIcon(i)));
                                  ^
    (see https://errorprone.info/bugpattern/FutureReturnValueIgnored)
  Did you mean 'var unused = this.icon.getAsync(i -> GuiHelper.runInEDT(() -> this.image.setIcon(i)));' or to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\ImageColorPicker.java:149: ����: [UnusedMethod] Method 'drawColorIndicator' is never used.
    private void drawColorIndicator(Graphics2D g, BufferedImage i, Rectangle visibleRectangle, Point p, Color current,
                 ^
    (see https://errorprone.info/bugpattern/UnusedMethod)
  Did you mean to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\ImageColorPicker.java:61: ����: [UnusedVariable] The field 'detectedSigns' is never read.
    private Boolean detectedSigns;
                    ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\ImageColorPicker.java:56: ����: [UnusedVariable] The field 'pointInComponent' is never read.
    private Point pointInComponent;
                  ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\ImageColorPicker.java:60: ����: [UnusedVariable] The field 'detectionOutlines' is never read.
    private Boolean detectionOutlines;
                    ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\ImageColorPicker.java:202: ����: [UnusedVariable] The field 'visibleRectangle' is never read.
        private Rectangle visibleRectangle;
                          ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\imageinfo\ClipboardAction.java:89: ����: [AlmostJavadoc] This comment contains Javadoc or HTML tags, but isn't started with a double asterisk (/**); is it meant to be Javadoc?
    public void actionPerformed(ActionEvent e) {
                ^
    (see https://errorprone.info/bugpattern/AlmostJavadoc)
  Did you mean '/**'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\layer\geoimage\MapillaryImageEntry.java:427: ����: [MissingOverride] getImageURI implements method in IImageEntry; expected @Override
    public URI getImageURI() {
               ^
    (see https://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public URI getImageURI() {'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\utils\DetectionVerification.java:32: ����: [DoNotCallSuggester] Methods that always throw an exception should be annotated with @DoNotCall to prevent calls at compilation time vs. at runtime (note that adding @DoNotCall will break any existing callers of this API).
    public static boolean vote(ImageDetection<?> detection, TYPE type) {
                          ^
    (see https://errorprone.info/bugpattern/DoNotCallSuggester)
  Did you mean '@DoNotCall("Always throws java.lang.UnsupportedOperationException") public static boolean vote(ImageDetection<?> detection, TYPE type) {'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\layer\MapillaryCustomizeDrawingAction.java:50: ����: [JdkObsolete] It is very rare for LinkedList to out-perform ArrayList or ArrayDeque. Avoid it unless you're willing to invest a lot of time into benchmarking. Caveat: LinkedList supports null elements, but ArrayDeque does not.
        layers = new LinkedList<>();
                 ^
    (see https://errorprone.info/bugpattern/JdkObsolete)
  Did you mean 'layers = new ArrayList<>();'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\layer\MapillaryLayer.java:195: ����: [LongDoubleConversion] Conversion from long to double may lose precision; use an explicit cast to double if this was intentional
        this.dateScale.setRange(Instant.now().minus(4 * 365L, ChronoUnit.DAYS).getEpochSecond(),
                                                                                             ^
    (see https://errorprone.info/bugpattern/LongDoubleConversion)
  Did you mean 'this.dateScale.setRange((double) Instant.now().minus(4 * 365L, ChronoUnit.DAYS).getEpochSecond(),'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\layer\MapillaryLayer.java:196: ����: [LongDoubleConversion] Conversion from long to double may lose precision; use an explicit cast to double if this was intentional
            Instant.now().getEpochSecond());
                                        ^
    (see https://errorprone.info/bugpattern/LongDoubleConversion)
  Did you mean '(double) Instant.now().getEpochSecond());'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\gui\workers\MapillarySequenceDownloader.java:190: ����: [LockNotBeforeTry] Prefer obtaining the lock for dsLock outside the try block. That way, if #lock throws, the lock is not erroneously released.
            dsLock.lock();
                       ^
    (see https://errorprone.info/bugpattern/LockNotBeforeTry)
  Did you mean 'dsLock.lock();try {'?
D:\code\Mapillary\src\main\java\org\openstreetmap\josm\plugins\mapillary\utils\MapillarySequenceUtils.java:29: ����: [UnusedVariable] The field 'SEQUENCE_CACHE' is never read.
    private static final CacheAccess<String, IWay<?>> SEQUENCE_CACHE = JCSCacheManager.getCache("mapillary:sequences");
                                                      ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line or 'static { JCSCacheManager.getCache("mapillary:sequences"); }'?
33 ������
  ? Finished after 24.73 seconds.

-----------------------------------

是什么原因导致的这个问题，需要什么样的环境才可以正常导出。目前导出的jar文件在josm中打开，登录后会弹出 更新插件 页面，已经是最新了。
![image](https://github.com/JOSM/Mapillary/assets/23569345/0eae9d8e-6887-4331-b7d2-260a211cf5f8)
![image](https://github.com/JOSM/Mapillary/assets/23569345/24971700-ac09-4b48-b716-dc93ebcfdea6)

反馈的信息是（没有提交）
Relative:URL: ^/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2023-08-29 13:38:40 +0200 (Tue, 29 Aug 2023)
Revision:18822
Build-Date:2023-08-30 01:30:57
URL:https://josm.openstreetmap.de/svn/trunk

Identification: JOSM/1.5 (18822 zh_CN) Windows 10 64-Bit
OS Build number: Windows 10 Home China 2009 (19045)
Memory Usage: 387 MB / 2004 MB (214 MB allocated, but free)
Java version: 17.0.8+9-LTS-211, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Look and Feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
Screen: \Display0 1920×1080 (scaling 1.00×1.00) \Display1 2560×1440 (scaling 1.00×1.00)
Maximum Screen Size: 2560×1440
Best cursor sizes: 16×16→32×32, 32×32→32×32
System property file.encoding: GBK
System property sun.jnu.encoding: GBK
Locale info: zh_CN
Numbers with default locale: 1234567890 -> 1234567890
Dataset consistency test: No problems found

Plugins:
+ Mapillary (2.2.0)
+ apache-commons (36034)

Last errors/warnings:
- 00000.487 W: extended font config - overriding 'filename.Myanmar_Text=mmrtext.ttf' with 'MMRTEXT.TTF'
- 00000.489 W: extended font config - overriding 'filename.Mongolian_Baiti=monbaiti.ttf' with 'MONBAITI.TTF'
- 00001.880 W: Unable to request certificate of https://roottest-g3.pkioverheid.nl
- 00002.246 W: Unable to request certificate of https://roottest-g3.pkioverheid.nl
- 00009.171 W: java.nio.file.FileSystemException: %UserProfile%\AppData\Local\Temp\josm_exec_powershell_2252032509474350440.txt: 另一个程序正在使用此文件，进程无法访问。
- 00009.172 W: Unable to request certificate of https://grca.nat.gov.tw
- 00160.470 E: java.lang.NumberFormatException: For input string: ""6640379272678125" "
- 00454.250 E: 
- 00454.256 E: Handled by bug report queue: jakarta.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: Thread-8 (90)
jakarta.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
	at org.eclipse.parsson.JsonParserImpl.parsingException(JsonParserImpl.java:455)
	at org.eclipse.parsson.JsonParserImpl.access$1000(JsonParserImpl.java:53)
	at org.eclipse.parsson.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:443)
	at org.eclipse.parsson.JsonParserImpl.next(JsonParserImpl.java:363)
	at org.eclipse.parsson.JsonReaderImpl.readObject(JsonReaderImpl.java:84)
	at org.openstreetmap.josm.plugins.mapillary.oauth.OAuthPortListener.run(OAuthPortListener.java:92)

**Comment by tsmock** [comment]
Looking at the stack trace, I suspect you have some kind of network issue. I was able to login myself. Alternatively, you have something sending garbage to the port we are listening on (`8763`). Or (if you are in China), the government might be screwing things up.

For the build issues, I have no clue what is going on; it works on my machine using `./gradlew build`.

The reason why I am throwing the exception instead of catching and suppressing it is just in case Mapillary changes the API endpoint on me. I'd rather have users report issues like this than wonder why they cannot log in.
