### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by ireun** [JOSM/Mapillary#240]
![image](https://github.com/user-attachments/assets/cc386f60-68c2-4b16-8f31-5b3aec47fa72)
Pretty fast JOSM get's to enormous memory usage when using Mapillary plugin. 
It seems that every time I switch to 'next pic' the heap memory rises by the size of that photo.
Caching problem? Shouldn't the photos be saved to disk, rather than kept in memory?

**Comment by ireun** [comment]
Sure, here's a little video of this happening, would you like me to also post some mem dumps or something?
https://streamable.com/4tbhun
After just 60s the mem size rises from 5.4G to 7.3G, and after another 60s to 9.3G.

**Comment by tsmock** [comment]
Go for it.

If I don't do anything about this in January, poke this issue again. There are good odds that I'll have forgotten about this.

**Comment by ireun** [comment]
Some more digging:
![image](https://github.com/user-attachments/assets/ad6496e2-2c8f-400a-bc32-b7d933943a74)
![image](https://github.com/user-attachments/assets/cb029a00-9c5c-447e-83e6-e021cb50ab07)
Seems that MapillaryImageEntries cache is kept in memory?

**Comment by ireun** [comment]
I've experimented a bit and found that initializing CACHE in MapillaryImageEntry with something like 
```Java
private static final CacheAccess<Long, MapillaryImageEntry> CACHE =
        JCSCacheManager.getCache("mapillary:mapillaryimageentry", 1, 0, null);
```

seems to work just fine, no more excessive heap usage. Waiting for your opinion on this @tsmock :)

**Comment by tsmock** [comment]
Documentation on `JCSCacheManager.getCache`:
```java
    /**
     * [...]
     * @param maxMemoryObjects  number of objects to keep in memory
     * @param maxDiskObjects    maximum size of the objects stored on disk in kB
     * @param cachePath         path to disk cache. if null, no disk cache will be created
     * @return cache access object
     */
    public static <K, V> CacheAccess<K, V> getCache(String cacheName, int maxMemoryObjects, int maxDiskObjects, String cachePath) {[...]}
```

The current code just makes a cache with defaults, `getCache(cacheName, DEFAULT_MAX_OBJECTS_IN_MEMORY.get(), 0, null);` where `DEFAULT_MAX_OBJECTS_IN_MEMORY` is `1000`.

We can do the following instead:

```java
private static final CacheAccess<Long, MapillaryImageEntry> CACHE =
        JCSCacheManager.getCache("mapillary:mapillaryimageentry", Config.getPref().getInt("mapillary.jcs.cache.max_objects_in_memory", 10), 0, null);
```

I want to keep at least the previous and next few images in memory, if at all possible. It would also be possible to make a GUI preference setting in Mapillary settings for it as well.

Thank you for debugging. :)
