### ISSUE TITLE
Add more traffic signs

### ISSUE THREAD

**Issue by overflorian** [JOSM/Mapillary#26]
Hi,
First of all, thanks so much for this plugin that I use on a weekly basis. It really allows a precise mapping in JOSM.

Would it be possible to add the wild animals traffic sign in the filter ?
I detailed this sign on the wiki: https://wiki.openstreetmap.org/wiki/Proposed_features/animal_crossing
I saw in your Trello that adding more generic traffic signs is on your list, so maybe it's already planned soon?

I run a side project (cf. https://github.com/overflorian/panneauxbiche) to map wild animals signs worldwide and your help would be much appreciated.

Regards

PS : I took the habit to add "mapillary=[mapillary_key]" on OSM objects thanks to this plugin. Is that something you do too?

**Comment by nokutu** [comment]
First, don't use that trello board. I only used it during the initial part of the development, so it's really out of date.

About the sign. It looks like Mapillary supports it in every country, so it shouldn't be a problem to add it to the filter.

And about the tag. At least myself, I have never used it.

**Comment by overflorian** [comment]
Thank you for your answer, it looks like a wonderful news. Therefore when do you think you could implement this traffic sign?
I look forward for more exciting mapping, thanks

**Comment by nokutu** [comment]
I'm pretty busy during weekdays, but I think I'll have time to implement it during the weekend. Shouldn't take long.

**Comment by overflorian** [comment]
Fantastic, thanks in advance

**Comment by eneerhut** [comment]
@overflorian is the sign you need in [our list](https://www.mapillary.com/developer/api-documentation/)? If so, then perhaps we can close this issue.

**Comment by overflorian** [comment]
Yes, the sign i'm looking for is warning--wild-animals--g6
In JOSM there is still the same amount of signs, so i'm not sure why you'd consider this issue as closed. Thanks

**Comment by eneerhut** [comment]
Thanks @overflorian. Hmm I thought JOSM was displaying every sign in our taxonomy. Do you have a lat/lon with a sign that you think is missing this is actually in our taxonomy?
@jpietri have you seen this issue?

**Comment by eneerhut** [comment]
![image](https://user-images.githubusercontent.com/11349863/62756674-f98e1600-babb-11e9-9be2-0f756f202c99.png)
@overflorian I have found an example of `warning--wild-animals--g1` but not `warning--wild-animals--g6`. Do you have a lat/lon where you know one is located so we can see whether JOSM is displaying it?

**Comment by tsmock** [comment]
The traffic sign/point object layers now use mapcss to select images. If there are still missing signs, feel free to either (a) file a bug report, (b) provide an image for it with the filed bug report (preferred), or (c) write your own mapcss style sheet. If a sign doesn't have an image (that would be a squarish white icon), it does need an icon (although some of them cannot really have an icon, due to being too general).
