### ISSUE TITLE
When filtering by user, keystrokes should not be treated as global keyboard shortcuts

### ISSUE THREAD

**Issue by floscher** [JOSM/Mapillary#35]
When you have the filter dialog open and type in a username, containing letters like `S`, `A` or `W` these letters are added to the text field, but also the global keyboard shortcuts of JOSM are fired.

The desired behaviour would be that the keystrokes are captured by the focused component (the TextField), but don't count as keyboard shortcuts (at least when neither `Ctrl` nor `Alt` is pressed simultaneously).

![grafik](https://cloud.githubusercontent.com/assets/3904348/22559071/46f7c924-e970-11e6-96ca-b04420380678.png)

**Comment by giackserva** [comment]
I think this would be fixed by using DisableShortcutsOnFocusGainedTextField instead of JTextField

**Comment by floscher** [comment]
Thank you for the suggestion! I switched the `JTextField` for a `DisableShortcutsOnFocusGainedTextField`. This change will roll out with the next release.
