### ISSUE TITLE
Please remove protected branch feature

### ISSUE THREAD

**Issue by stoecker** [JOSM/Mapillary#37]
Hello,

The master branch uses protected branch feature which makes it impossible to commit to the branch from the SVN reposity. As The I18n update infrastructure does use this setup and I18n update is no longer possible with Mapillary.

But on of the requirements of the automatic I18n translation is that updates can be done this way. When this is no longer possible Mapillary has no longer the right to use that infrastructure.

Please change the settings, so it's again possible to commit the i18n stuff in data via the SVN interface.

**Comment by floscher** [comment]
Sure, I updated the external, so you can push i18n changes to this repo again.

Sorry, that we violated these guidelines, I haven't heard of this hard requirement before. Are these guidelines documented somewhere?
