### ISSUE TITLE
Auto-correlate images without GPS using a provided GPX file (e.g. images from the app)

### ISSUE THREAD

**Issue by drkludge** [JOSM/Mapillary#47]
### Basic information
* Platform: `Android 6.0.1`
* Version: `3.43` 
* JOSM Version `11826`
* Mappilary Plugin Version `1.4.2`

### Steps to reproduce behavior
 1. Use new version Android 3.43 to generate a sequence.  [Perhaps IOS version of the capture app already uses a separate file for the gps coordinates.](http://forum.mapillary.io/t/transferred-images-to-computer-what-now/599)
 2. Use JOSM imports into a sequence with JOSM.
 3. Try to upload files.

### Expected behavior
Use JOSM Mapillary plugin to upload images as a work around to https://github.com/mapillary/mapillary_issues/issues/2513

### Actual behavior

The images do not have gps meta data so that they can be uploaded.  I have attached a zip file that includes sequence of two files and the new .gpx meta data file.  I can provide another file with more images if that will help.

### Additional information

I may be able to use another JOSM plugin to add the gps coordinates back into the image files.  I don't know if you need another process to handle these images.  I am guessing that the Mapillary JOSM plugin is designed to create a sequence created by applications other than a Mapiillary phone app.

![image](https://cloud.githubusercontent.com/assets/1669057/24832806/df88222c-1c6c-11e7-83ca-56094927fe26.png)

[2017_04_08_13_06_27_878.zip](https://github.com/JOSM/Mapillary/files/908133/2017_04_08_13_06_27_878.zip)

**Comment by floscher** [comment]
This sounds a lot like #14.

The plugin does not recognize the GPS coordinates if they are not in the standard EXIF format.

As noted in e.g. openstreetcam/upload-scripts#17, the Mapillary app stores the coordinates in the `ImageDescription` field as "some sort of proprietary JSON structure", or to quote @jlevente:
> In this case, when `ImageDescription` tag exists (apps write it to the EXIF), our system uses `MAPLatitude` and `MAPLongitude` inside `ImageDescription` (which is a JSON object) instead of using the standard EXIF tags.

**Comment by drkludge** [comment]
@floscher These are two different issues.  The resent version of the Android application no longer stores gps information **in the image** as EXIF formatted data as the image is captured for performance reasons.  I'd close #14 in favor of this report. The Mapillary jpg files are that, just jpeg files with no geo data in image header.

**Comment by floscher** [comment]
OK, then I'll reopen, didn't know that.

Are the images then only matched using timestamp? Do the two images you provided and the GPX file belong together? I can't find the timestamps of the images in the GPX file.

cc @peterneubauer

**Comment by peterneubauer** [comment]
We will add the writing of GPS into the exif back, but potentially it
should be a time synced combination of gpx and images. That will work for
nit only mapillary images but all capture devices.

**Comment by drkludge** [comment]
[2017_04_08_10_47_39_711.zip](https://github.com/JOSM/Mapillary/files/911386/2017_04_08_10_47_39_711.zip)

@floscher Here is another zip file.  There are only 21 images of a cafe's patio area.  There are 162 trkpt tags in the LEGACY_CAM_0_2017_04_08_10_47_39_728.gpx file.

**Comment by floscher** [comment]
It looks as if this could soon have a solution.
I'm working on an enhancement, which would allow you to import images from a `GeoImageLayer` (see https://github.com/JOSM/Mapillary/issues/54#issuecomment-298346608). JOSM already let's you import un-geotagged images into such a layer and correlate them with a GPX file. So you could then import these images into the Mapillary layer via that `GeoImageLayer`.
Not the most straightforward solution, but the easiest to get this working as soon as possible.

**Comment by floscher** [comment]
[`v1.5.4`](https://github.com/JOSM/Mapillary/releases/tag/v1.5.4) of the plugin is now released, which should allow importing of non-geotagged images and correlating them with a GPX file:
* open the images in JOSM (either via `File › Open` or by dragging them into the map view)
* correlate them with the GPX file using the dialog that should pop up
* Then use `File › Import images` and the images should appear in the Mapillary layer
