### ISSUE TITLE
User-Filter: filter for more than one user

### ISSUE THREAD

**Issue by dex2000** [JOSM/Mapillary#51]
add possibility to show sequences of more than 1 users - like 

    user1,user2

**Comment by floscher** [comment]
I'd prefer to have multiple textfields, one per user to filter for. That would avoid problems with e.g. usernames, which contain commas.
But yes, that'd be a useful feature.

**Comment by tsmock** [comment]
Unfortunately, the v4 API does not return any user information, so I'm closing this.
