### ISSUE TITLE
Time-filter: don't use older than

### ISSUE THREAD

**Issue by dex2000** [JOSM/Mapillary#53]
imho it should be better to use a time range like 

show from [date in past] to [today]

then you can exlude newest to.

This a little bit trickier: possibility to exclude a range (sometimes you want to exclude all pictures from a highway-construction)

**Comment by eneerhut** [comment]
Yes agree @dex2000. Would be handy to see imagery over a specific time frame. Excluding more recent imagery.

**Comment by EdLoach** [comment]
Found this while checking before suggesting similar. Use case: a street with shops with high rate of churn gets Mapillary surveyed regularly - would be good to be able to filter to latest survey.

**Comment by taylorsmock** [comment]
May be fixed in 46f9e2b55771fe841530e60f05ecd2ac98fdea1e.

**Comment by dex2000** [comment]
thx a lot
