### ISSUE TITLE
Improve upload experience

### ISSUE THREAD

**Issue by floscher** [JOSM/Mapillary#55]
While images are uploaded the progress should be shown.

Maybe change placement of "Upload images" button, maybe bring changeset view and uploading together?!

Depending on what exactly caused #54, either fix a possible bug that disabled the upload action or improve UI to avoid this from happening.

**Comment by tsmock** [comment]
I'm going to close this since I had to remove the upload functionality with the v3 -> v4 transition, and Mapillary has not opened up the API documentation for uploads.
