### ISSUE TITLE
Add visual guides for what part of panoramic/spherical images is in which direction

### ISSUE THREAD

**Issue by floscher** [JOSM/Mapillary#57]
I'm imagining something not unlike this sketch:
![mockup](https://cloud.githubusercontent.com/assets/3904348/25784447/8f2e374a-336d-11e7-9e61-6ba21d339df2.png)
This would be added to the image display for 360° images (only).

**Comment by tsmock** [comment]
Fixed in a4822b859baae75e2b65d375bf61c5a4a475f432 and cfbef1f1eb756876488f176fb4fc427e2d704054
