### ISSUE TITLE
Enable deeper zooming for image viewer / Download more detailed versions of 360° images

### ISSUE THREAD

**Issue by andrewharvey** [JOSM/Mapillary#60]
This is what zooming into one of my photos looks like in the mapillary.com/app website:
![selection_645](https://user-images.githubusercontent.com/117278/27686314-9b939026-5d15-11e7-8155-2eb5ddb09ca4.png)

This is as far as I can zoom in in the JOSM plugin:
![selection_646](https://user-images.githubusercontent.com/117278/27686332-acced102-5d15-11e7-9181-c84b301936d1.png)

I can read the sign in the former but not the latter. It would be great if you could zoom in more in the image in JOSM.

Maybe this is the line to change?
 https://github.com/JOSM/Mapillary/blob/master/src/org/openstreetmap/josm/plugins/mapillary/gui/MapillaryImageDisplay.java#L104

**Comment by eneerhut** [comment]
Good spot @andrewharvey. Do you have the sequence link?

**Comment by andrewharvey** [comment]
@eneerhut This is the photo https://www.mapillary.com/map/im/AC5syj-Vw_s0RVl35imq2Q

**Comment by floscher** [comment]
@andrewharvey Thank you for bringing this up and even pointing at the line in the source code 👍 😄 

But it looks like this won't cut it. I downloaded the exact image, which the plugin gets from the server: https://d1cuyjsrcm0gby.cloudfront.net/AC5syj-Vw_s0RVl35imq2Q/thumb-2048.jpg

This is the interesting portion of the image scaled up by 10×:
![grafik](https://user-images.githubusercontent.com/3904348/27691981-da1b19e8-5ce5-11e7-8b7c-0c1900fbd1db.png)

So no amount of scaling would help. @eneerhut: Is the web viewer doing additional post processing of the image like sharpening? Or are there more detailed versions of the images available for download?

**Comment by floscher** [comment]
The webapp uses the image https://d2qb1440i7l50o.cloudfront.net/AC5syj-Vw_s0RVl35imq2Q/1024,1024,1024,1024/1024,1024/0/default.jpg?origin=mapillary.webgl .

This time I scaled the interesting portion of that image 5×:
![grafik](https://user-images.githubusercontent.com/3904348/27692770-d80339c2-5ce7-11e7-8f5d-4a37c2b94162.png)

That image is depicting the sign in more detail (the sign occupies more pixels of the image). But I doubt this URL is part of an official API for other apps to use.
The official APIv3 only declares four image URLs of which the JOSM plugin already uses the most detailed: https://a.mapillary.com/#retrieve-image-sources

cc @eneerhut
cc @peterneubauer

**Comment by eneerhut** [comment]
@floscher I think you hit the nail on the head. Let's look into which images are being publicly exposed and if a higher quality one can be made available for OSM integrations.

**Comment by miurahr** [comment]
In my experience with #79 patch, I can download a detailed version when making photo window enlarge enough. It seems to be a logic to change thumbnails size according to window size. Small window  leads small thum and large window triggers large image. I can see it on debug log.

**Comment by tsmock** [comment]
The Mapillary v4 API now has a `thumb_original_url` field. I'm going to default to that until I get around to implementing some kind of zoom listener functionality in the JOSM image viewer.

Rather unfortunately, this is going to increase network traffic.
