### ISSUE TITLE
"add mapillary tag" is broken

### ISSUE THREAD

**Issue by dex2000** [JOSM/Mapillary#61]
Short version: 
Click: "add mapillary tag"
Try upload
Error: no data was changed

Long Version:
https://josm.openstreetmap.de/ticket/15109

**Comment by floscher** [comment]
Thank you for reporting this issue. I fixed it in commit e111ae604931e3c767979716ffb2fed6f251c3df and it will roll out with the next release after [`v1.5.6`](https://github.com/JOSM/Mapillary/releases/tag/v1.5.6).
