### ISSUE TITLE
Build problems on Windows

### ISSUE THREAD

**Issue by floscher** [JOSM/Mapillary#62]
Today I tested, how well building this project on Windows works.
And I realized, that there are multiple problems preventing the build from passing.

First I had problems with the character encoding of the source code, the `:compileJava` task failed.
But even after setting the encoding for the compile tasks (fix not yet pushed to GitHub), there were multiple unit tests failing. Part of them also because of encoding issues. For example because of the umlaut `Ä` in this line (somehow I knew, when adding that line, that someday this character will point me at an encoding issue :wink:): https://github.com/JOSM/Mapillary/blob/2d97ef44352a628fdf006e2ff905c20aec5e17cc/test/unit/org/openstreetmap/josm/plugins/mapillary/utils/api/JsonUserProfileDecoderTest.java#L73
Other tests were failing, because a lockfile of the JCS cache existed, so the test could not read/write to/from the cache.

If there is somebody using Windows, who could help investigate the issue and test out new versions that try to fix this, it would be great if you could give it a try:
```batchfile
git clone https://github.com/JOSM/Mapillary.git
gradlew build
```

**Comment by don-vip** [comment]
```
PS C:\GIT\Mapillary> .\gradlew clean build

> Task :pmdMain
116 PMD rule violations were found. See the report at: file:///C:/GIT/Mapillary/build/reports/pmd/main.html

> Task :pmdTest
24 PMD rule violations were found. See the report at: file:///C:/GIT/Mapillary/build/reports/pmd/test.html

> Task :spotbugsMain
Scanning archives (147 / 147)
2 analysis passes to perform
Pass 1: Analyzing classes (1037 / 1037) - 100% complete
Pass 2: Analyzing classes (144 / 144) - 100% complete
Done with analysis
SpotBugs rule violations were found. See the report at: file:///C:/GIT/Mapillary/build/reports/spotbugs/main.html

> Task :spotbugsTest
Scanning archives (48 / 48)
2 analysis passes to perform
Pass 1: Analyzing classes (297 / 297) - 100% complete
Pass 2: Analyzing classes (39 / 39) - 100% complete
Done with analysis
SpotBugs rule violations were found. See the report at: file:///C:/GIT/Mapillary/build/reports/spotbugs/test.html


BUILD SUCCESSFUL in 1m 20s
17 actionable tasks: 17 executed
```

**Comment by floscher** [comment]
Great, then that's now working again. Thanks!
