### ISSUE TITLE
Deadlock in unit tests

### ISSUE THREAD

**Issue by don-vip** [JOSM/Mapillary#63]
One unit test is hanging:
https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/jdk=JDK8/1011/console

```
test:
     [echo] Running unit tests with JUnit
[jacoco:coverage] Enhancing junit with coverage
    [junit] Running org.openstreetmap.josm.plugins.mapillary.AbstractTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.162 sec
    [junit] Running org.openstreetmap.josm.plugins.mapillary.ImportTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.559 sec
    [junit] Running org.openstreetmap.josm.plugins.mapillary.MapillaryAbstractImageTest
```

It kills our Jenkins server. It happened two times in two days, can you please look into it?

**Comment by floscher** [comment]
Sorry, sure I'll see what I can do. I introduced this in 4ece78895d5579fbe9b9e10ed1f34d722f706798, then realized the deadlock and rolled back the branch `trunk` to the commit before the bad commit.

But Jenkins already picked the bad commit up as ["revision 1214"](https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/1010/changes) and won't change the version back to 1213, which is now at the head of branch trunk.

I'll probably push some harmless commits to the trunk branch to make Jenkins change the revision.

**Comment by floscher** [comment]
This should now be fixed, I pushed 3 new commits 7e0f487c81a9996312c91ef88598bad73162bd32...2a9c34474e0fa6f09ed2418549db354b37f1f262 to `trunk`, so Jenkins will hopefully check out the new revision.

**Comment by floscher** [comment]
I'm so sorry. It [happened again](https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/jdk=JDK8/1013/console), I already pulled back the change long before Jenkins pulled the latest changes from GitHub, but apparently it got the bad change nevertheless.

**Comment by floscher** [comment]
In 859ab683189addbed389bf80d201ebde07de293d I rewrote the unit tests (using `JOSMTestRules` from JOSM core) and I also revisited synchronization in `MapillaryLayer`, so now this issue should no longer happen.
I've seen, that `JOSMTestRules` times out the unit tests after 10s. Don't know if this is also true when a deadlock occurs, but it'll help definitely.

**Comment by don-vip** [comment]
OK now the test timeouts at 10 seconds. Did you find a way to fix the issue?

**Comment by don-vip** [comment]
I'm reopening the issue as our Jenkins job is unstable everyday because of this failing test.
