### ISSUE TITLE
Plug-in Mapillary: object layer fills the recognited object instead of only marking it

### ISSUE THREAD

**Issue by yopaseopor** [JOSM/Mapillary#64]
The detection works in its way.
But the problem is that the detector full-fills the mapillary pic with the result of the detection, avoiding the possibility of view the real detected object. If the object would be wrong recognized you would'nt be able to see it because you only watch the result of the recognition instead of the real object. You can see it in this screen capture. I have marked right and wrong behaviour. With the orange mark will be enough to mark the sign.

<a href="https://imgur.com/lwico7D"><img src="https://i.imgur.com/lwico7D.png" title="source: imgur.com" /></a>

JOSM 12542
Windows 10

**Comment by floscher** [comment]
You can turn that off by opening the Mapillary info dialog by clicking on this symbol in the sidebar on the left: ![mapillary-info](https://cdn.rawgit.com/JOSM/Mapillary/3aca09010398158a61e961e4e963dd36a5c1ecb2/images/dialogs/mapillary-info.svg)

There you have a checkbox to switch the overlay on or off (see the bottom right of the following screenshot).

![](https://cloud.githubusercontent.com/assets/3904348/24870038/583bf1a4-1e15-11e7-8086-e33972044fa7.png)

I know this is somewhat hidden, but that's where this option made most sense for me when adding the traffic signs. If you have a suggestion for better placement, feel free to let me know.

(For reference:  This has been brought up in https://github.com/JOSM/Mapillary/issues/46#issuecomment-293057259 )
