### ISSUE TITLE
change URL for "view in Browser"

### ISSUE THREAD

**Issue by dex2000** [JOSM/Mapillary#69]
Please add possibility to change the URL via preferences for button "View in Browser". (or maybe change it hardcoded...)

The only Link i want in JOSM is to unblur Images/Signs etc. so i dont need to view the image in Browser (i can see it still in JOSM...) and then click here and click there and there...

**Comment by floscher** [comment]
Yes, good idea. I can add that.

But I think this won't solve the problem you are describing.

As far as I know, there is no such link, which directly opens the blur editor.

**Comment by dex2000** [comment]
I can see for example:
https://www.mapillary.com/app/?focus=photo&pKey=drtFmqi3dAwLQTbA7pDbAg&lat=50.9609&lng=10.020086111111112&z=17 (photo)
vs 
https://www.mapillary.com/app/blur?focus=photo&pKey=drtFmqi3dAwLQTbA7pDbAg&lat=50.9609&lng=10.020086111111112&z=17&menu=false (unblur)

**Comment by floscher** [comment]
Ah, great! Last time I looked, there wasn't such link. I'll definitely add that soon.

**Comment by floscher** [comment]
This change has just landed in [version `v1.5.9`](https://github.com/JOSM/Mapillary/releases/tag/v1.5.9) of the Mapillary plugin.
