### ISSUE TITLE
"view on mapillary" in JOSM-Tag-Editor missing

### ISSUE THREAD

**Issue by dex2000** [JOSM/Mapillary#70]
iirc there was 10 days ago or so in Josm the possibility to mark the mapillary-tag in Tag-editor for "view on mapillary" similar to "goto OSM-Wiki" or "view on taginfo".

This functionality is gone. Have tried older JOSM-Version and there its gone too, so i think it was on the mapillary-plugin.

**Comment by floscher** [comment]
I don't think, that the Mapillary plugin did provide this link.

Could it be, that it was the [tag2link plugin](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Tag2Link)? That plugin adds such links for several tags, including `((ref|source):)?mapillary=*`

**Comment by dex2000** [comment]
Uuuh, possible, have deleted som plugins here, will check that later and close.

**Comment by dex2000** [comment]
Jep, tag2link was the problem, sry.
