### ISSUE TITLE
Add Colour picker

### ISSUE THREAD

**Issue by stefanb** [JOSM/Mapillary#75]
When adding `colour` tags (https://wiki.openstreetmap.org/wiki/Key:colour ), eg 
* building:facade:colour
* building:colour
* roof:colour

it would be very handy to get the exact hex color code easily from the Mapillary images.

One option would  is to just copy the hex colour code to the clipboard and let user add the tag. Better, but more complex option would be to add the complete tag with the chosen colour value to the currently selected OSM object.

**Comment by tsmock** [comment]
@GhostFoxSledgehammer has implemented this. See 7b78a9382e9ddc0c5329f4f364ed6597cb61d30d.
