### ISSUE TITLE
Update to JOSM 13643

### ISSUE THREAD

**Issue by don-vip** [JOSM/Mapillary#76]
https://josm.openstreetmap.de/changeset/13643/josm removed the IOException declarations from several methods of `JCSCacheManager`.

Mapillary plugin must be updated.

**Comment by floscher** [comment]
I'm currently at it :wink:, update is coming soon. At the moment working on tests that time out.

**Comment by floscher** [comment]
Release is done. Fingers crossed, that it works as expected :crossed_fingers: .
I released two versions `v1.5.11`: One compatible with JOSM before 13643 and one for later versions. The later one contains the download link for the other one in the manifest. So normally JOSM should gracefully downgrade if someone uses an "older" JOSM version.

https://github.com/JOSM/Mapillary/releases/tag/v1.5.11%2Bpre13643
https://github.com/JOSM/Mapillary/releases/tag/v1.5.11%2Bpost13643

**Comment by floscher** [comment]
I had to pull the `v1.5.11` version, it had a serious bug (StackOverflowException), which I introduced when trying to rework initialization of the Mapillary layer in order to avoid a deadlock. :disappointed: 
Looks as if there's a more thorough fix needed. I'll soon release `v1.5.12` when it's ready

**Comment by don-vip** [comment]
What's the status? Jenkins is failing for a week now: https://josm.openstreetmap.de/jenkins/job/JOSM-Plugins/

**Comment by don-vip** [comment]
Even if a release is not made, the source code should always compile ;)

**Comment by floscher** [comment]
Ah sorry, thanks for the ping. The build should be fixed now: https://travis-ci.org/JOSM/Mapillary/builds/371746969

**Comment by floscher** [comment]
Now [`v1.5.12+post13643`](https://github.com/JOSM/Mapillary/releases/tag/v1.5.12%2Bpost13643) is released which includes the change.
