### ISSUE TITLE
v3/ objects API deprecated, causing errors

### ISSUE THREAD

**Issue by cbeddow** [JOSM/Mapillary#83]
Screenshot here (Hungarian): 

![image](https://user-images.githubusercontent.com/10554922/49181166-f05a8000-f356-11e8-8820-cc739535cb44.png)

When the objects layer is activated, an error is returned. The v3/objects API is deprecated. In order to retrieve traffic signs, it needs to use `https://a.mapillary.com/v3/map_features?layers=trafficsigns&client_id=...` in order to retrieve these. I believe the same client ID will work.

Can someone make this update?

**Comment by miurahr** [comment]
Seems duplicated with #73, #80

**Comment by floscher** [comment]
With #84 this is fixed and will be released with the next version of the plugin.
