### ISSUE TITLE
Mapillary Image Window - Next Image Flickering

### ISSUE THREAD

**Issue by Firefishy** [JOSM/Mapillary#86]
When click "Previous picture" or "Next picture" in the Mapillary image window the window contents switches very briefly to a fully white window displaying "No image selected" and then replaces with the image.

The flicker to to this white window with text causes a lot of eye strain and the repeated flick is annoying.

Ideally the window should should just display the new image without the flicker of text.

**Comment by jpietri** [comment]
Hi @Firefishy!
Have you tried the [latest version](https://github.com/JOSM/Mapillary/releases/tag/v1.5.18)? It supposedly solved your issue by _adding an option for dark mode that shows a dark background for the image viewer_.

**Comment by Firefishy** [comment]
Much better. Thank you. :eye: :+1:
